# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@linux']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kconfigwidgets' : '@latest'
    'frameworks/kwindowsystem' : '@latest'
    'frameworks/kxmlgui' : '@latest'
    'frameworks/kcontacts' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kmime' : '@same'
    'pim/eventviews' : '@same'
    'frameworks/kirigami' : '@latest'

